### ISSUE TITLE
ClusterCIDR Validation is Missing

### ISSUE THREAD

**Issue by mneverov** [kubernetes-sigs/node-ipam-controller#10]
[Validation](https://github.com/kubernetes-sigs/node-ipam-controller/blob/main/pkg/apis/clustercidr/v1/validation/validation.go) is ported, but not wired up. Originally, it was set up via internal [storage registry](https://github.com/kubernetes/kubernetes/pull/121229/files#diff-79ea0926034aad04fd53e64bbd4e6b13096eef7a7efbea2572b147f2db52d478). It is too cumbersome to set up ApiServer just for it.

Options: webhooks or [k8s CEL](https://github.com/kubernetes/kubernetes/pull/121912).

**Comment by aojea** [comment]
> Options: webhooks or [k8s CEL](https://github.com/kubernetes/kubernetes/pull/121912).

no doubt, CEL if possible
