### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by ugur99** [kubernetes-sigs/node-ipam-controller#19]
It's really great to see a sig project that addresses the node CIDR management problem. We really like the idea and could definitely use it for our own vanilla Kubernetes clusters.

We’re currently weighing our options between writing our own custom controller and using/supporting this project. We just wanted to check in and ask about the maturity level of the project. Is it ready for production use or any plans about it?

**Comment by aojea** [comment]
It is a SIG Network project under kubernetes-sigs and is meant to be used in production, we added a good battery of tests and inherit some lessons from running it in production ... though it has not been widely used like other projects, we are promptly fixing the bugs or issues that are being reported.

**Comment by ugur99** [comment]
Thank you for your quick response @aojea! Then we will try to adopt it to our clusters. I'm closing this issue.
