### ISSUE TITLE
Improve README (and documentation)

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/node-ipam-controller#2]
We should have more detailed instructions on how to run , install and use the new node ipam controller

**Comment by uablrek** [comment]
Amen to that! Is `node-ipam-controller` a cloud provider? (I am trying to re-do my setup with the in-tree version)

**Comment by aojea** [comment]
> Is `node-ipam-controller` a cloud provider?

fixed now, I was thinking in another thing when I wrote the message XD, node ipam controller is agnostic of cloud provider or bare metal, just people has to disable the existing node-ipam controllers that run on the kube-controller-manager or cloud-controller-manager to avoid conflicts

**Comment by uablrek** [comment]
/assign

I am a member now :smile:

**Comment by uablrek** [comment]
I got it running now, but not with the POD. I create the CRDs and a `ClusterCIDR`, then I start in a shell on the controller with:
```
manager --kubeconfig=$KUBECONFIG
```
and the nodes all get's `podCIDRs`. Yay :smiley: 

How should the POD be used? I start with an empty cluster and kube-proxy waits for PodCIDRs, meaning that the `kubernetes` service is unavailable and the `node-ipam-controller` can't connect to the api-server to set the PodCIDRs. A classic "catch 22".

I can create a kubeconfig and mount a directory to fix things. I have "borrowed" from [calico](https://github.com/projectcalico/cni-plugin/blob/be4df4db2e47aa7378b1bdf6933724bac1f348d0/k8s-install/scripts/install-cni.sh#L104-L153) for similar things in the past.

But that is considerably harder than the currently provided POD chart.
