### ISSUE TITLE
Immutable fields are, in fact, not immutable.

### ISSUE THREAD

**Issue by ugur99** [kubernetes-sigs/node-ipam-controller#22]
I just noticed that I can change the `ipv4`, `ipv6`, and `nodeSelector` fields of the ClusterCIDR resource after provisioning. This seems unintended, as according to the CRD definition, these fields should be immutable.

**Comment by aojea** [comment]
Oh, thanks for reporting it, this was debated some time ago and the solution was to implement a webhook but I proposed to wait for CEL to be available and it seems we forget to follow  up.

@sarveshr7 @ameukam @mneverov this page describe how to implement CEL markers to make the fields inmutables

https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#immutablility-after-first-modification

Is any of you willing to take on this?


EDIT

I found it, it is WIP https://github.com/kubernetes-sigs/node-ipam-controller/pull/13 and the issue got closed by the bot https://github.com/kubernetes-sigs/node-ipam-controller/issues/10

**Comment by aojea** [comment]
@mneverov please assign it to yourself if you are going to work on this ,  @DhritiShikhar is also offering to help
