### ISSUE TITLE
Add K8s authors header

### ISSUE THREAD

**Issue by mneverov** [kubernetes-sigs/node-ipam-controller#25]
They `Copyright 2023 The Kubernetes Authors.` should be present in all files, also in boilerplate.

**Comment by aojea** [comment]
why?

this project is under kubernetes so it has to keep the copyright, now I notice we have this empty https://github.com/kubernetes-sigs/node-ipam-controller/blob/main/hack/boilerplate.go.txt

https://github.com/kubernetes-sigs/node-ipam-controller/blob/main/CONTRIBUTING.md#contributing-guidelines

**Comment by mneverov** [comment]
Currently, only few files have this header. I checked projects under k8s-sigs and some have the header, and some don't.
I'm for consistency either way. Let's add the header to all files and boilerplate too.

**Comment by mneverov** [comment]
Updated the description to add the headers.

**Comment by aojea** [comment]
> checked projects under k8s-sigs and some have the header, and some don't.
> I'm for consistency either way.

heh :) is not surprising :)
