### ISSUE TITLE
Replace Update with Patch

### ISSUE THREAD

**Issue by mneverov** [kubernetes-sigs/node-ipam-controller#38]
Currently, the allocator uses [Update](https://github.com/kubernetes-sigs/node-ipam-controller/blob/main/pkg/controller/ipam/multi_cidr_range_allocator.go#L1162) to reconcile existing ClusterCIDRs. MergePatch is a better option since only diff is sent. Replace Update with Patch.

**Comment by aojea** [comment]
> Currently, the allocator uses [Update](https://github.com/kubernetes-sigs/node-ipam-controller/blob/main/pkg/controller/ipam/multi_cidr_range_allocator.go#L1162) to reconcile existing ClusterCIDRs. MergePatch is a better option since only diff is sent. Replace Update with Patch.

it really depends, in this case we want to move the object to exactly the one we have, including the defaults, with mergepatch if someone modifies a field and we don't send the update, we don't reset it

**Comment by mneverov** [comment]
The only update we do is we set the finalizer and using PUT to send the whole CRD is wasteful, although we do not expect to operate on thousands of ClusterCIDR, hence this will never be a bottleneck. Closing.
