### ISSUE TITLE
Remove all "mneverov" references

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/node-ipam-controller#4]
They are everywhere. Most urgent is:
```
module github.com/mneverov/cluster-cidr-controller
```
in `go.mod`.

**Comment by ameukam** [comment]
References have been replaced in https://github.com/kubernetes-sigs/node-ipam-controller/pull/1. 

If you find more, feel free to open a PR to remove them.

**Comment by aojea** [comment]
I don't find any other https://github.com/search?q=repo%3Akubernetes-sigs%2Fnode-ipam-controller%20mneverov&type=code

let's close it by now

/close

**Comment by uablrek** [comment]
Sorry, I forgot a "git pull" :blush:
